FROM php:7.0.22-cli
#WORKDIR "/application"

# Install selected extensions and other stuff
#RUN apt-get update \
#    && apt-get -y --no-install-recommends install  php7.1-mysql php7.1-common php7.1-mbstring \
#    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

#RUN mkdir -p /tmp/MyReviewsReviews/cache && chmod 777 /tmp/MyReviewsReviews/cache