dist: bionic
services:
  - docker
env:
  global:
      - DOCKER_ENGINE_VERSION=19.03.13
      - DOCKER_COMPOSE_VERSION=1.24.1

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common build-essential
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io
  - sudo usermod -aG docker your-user
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
# Print out the current docker-compose version. Once this reports 1.6+ then we
  # do not need the following steps.
  - docker --version
  - docker-compose --version

script:
  - make up
  - make phpcs
  - make securitychecker
