version: '3'
services:
  php:
    build:
      context: docker/php
    volumes:
      - websrc:/var/www/html
      - ./docker/php.ini:/etc/php/7.0/cli/php.ini
    user: $UID
    working_dir: /var/www/html
    depends_on:
      - composer

  composer:
    build:
      context: docker/composer
    user: $UID
    volumes:
      - websrc:/app

    command: composer install --dev
    working_dir: /app
    environment:
      - COMPOSER_HOME=/home/composer

volumes:
  websrc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $PWD
